package com.tianfang.admin.mapper;

import com.tianfang.admin.pojo.SportAuthorization;
import com.tianfang.admin.pojo.SportAuthorizationExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SportAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int countByExample(SportAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int deleteByExample(SportAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int insert(SportAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int insertSelective(SportAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    List<SportAuthorization> selectByExample(SportAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    SportAuthorization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportAuthorization record, @Param("example") SportAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int updateByExample(@Param("record") SportAuthorization record, @Param("example") SportAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int updateByPrimaryKeySelective(SportAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_authorization
     *
     * @mbggenerated Fri Nov 13 12:55:14 CST 2015
     */
    int updateByPrimaryKey(SportAuthorization record);
}