package com.tianfang.admin.mapper;

import com.tianfang.admin.pojo.SportAdmin;
import com.tianfang.admin.pojo.SportAdminExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SportAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int countByExample(SportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int deleteByExample(SportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int insert(SportAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int insertSelective(SportAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    List<SportAdmin> selectByExample(SportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    SportAdmin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportAdmin record, @Param("example") SportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int updateByExample(@Param("record") SportAdmin record, @Param("example") SportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int updateByPrimaryKeySelective(SportAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_admin
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    int updateByPrimaryKey(SportAdmin record);
}