package com.tianfang.admin.mapper;

import com.tianfang.admin.pojo.SportMenu;
import com.tianfang.admin.pojo.SportMenuExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SportMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int countByExample(SportMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int deleteByExample(SportMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int insert(SportMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int insertSelective(SportMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    List<SportMenu> selectByExample(SportMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    SportMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportMenu record, @Param("example") SportMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int updateByExample(@Param("record") SportMenu record, @Param("example") SportMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int updateByPrimaryKeySelective(SportMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    int updateByPrimaryKey(SportMenu record);
}