package com.tianfang.news.mapper;

import com.tianfang.news.pojo.SportCoachTrain;
import com.tianfang.news.pojo.SportCoachTrainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportCoachTrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int countByExample(SportCoachTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int deleteByExample(SportCoachTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int insert(SportCoachTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int insertSelective(SportCoachTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    List<SportCoachTrain> selectByExample(SportCoachTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    SportCoachTrain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportCoachTrain record, @Param("example") SportCoachTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int updateByExample(@Param("record") SportCoachTrain record, @Param("example") SportCoachTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int updateByPrimaryKeySelective(SportCoachTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_coach_train
     *
     * @mbggenerated Fri Dec 25 11:51:40 CST 2015
     */
    int updateByPrimaryKey(SportCoachTrain record);
}