package com.tianfang.user.mapper;

import com.tianfang.user.pojo.SportUser;
import com.tianfang.user.pojo.SportUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int countByExample(SportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int deleteByExample(SportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int insert(SportUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int insertSelective(SportUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    List<SportUser> selectByExampleWithBLOBs(SportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    List<SportUser> selectByExample(SportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    SportUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") SportUser record, @Param("example") SportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") SportUser record, @Param("example") SportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int updateByExample(@Param("record") SportUser record, @Param("example") SportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int updateByPrimaryKeySelective(SportUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(SportUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_user
     *
     * @mbggenerated Fri Feb 26 16:18:22 CST 2016
     */
    int updateByPrimaryKey(SportUser record);
}