package com.tianfang.user.mapper;

import com.tianfang.user.pojo.SportShippingAddress;
import com.tianfang.user.pojo.SportShippingAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportShippingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int countByExample(SportShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int deleteByExample(SportShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int insert(SportShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int insertSelective(SportShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    List<SportShippingAddress> selectByExample(SportShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    SportShippingAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportShippingAddress record, @Param("example") SportShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int updateByExample(@Param("record") SportShippingAddress record, @Param("example") SportShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int updateByPrimaryKeySelective(SportShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_shipping_address
     *
     * @mbggenerated Tue Dec 01 14:17:07 CST 2015
     */
    int updateByPrimaryKey(SportShippingAddress record);
}