package com.tianfang.business.mapper;

import com.tianfang.business.pojo.SportSuggestionUser;
import com.tianfang.business.pojo.SportSuggestionUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportSuggestionUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int countByExample(SportSuggestionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int deleteByExample(SportSuggestionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int insert(SportSuggestionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int insertSelective(SportSuggestionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    List<SportSuggestionUser> selectByExample(SportSuggestionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    SportSuggestionUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportSuggestionUser record, @Param("example") SportSuggestionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int updateByExample(@Param("record") SportSuggestionUser record, @Param("example") SportSuggestionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int updateByPrimaryKeySelective(SportSuggestionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    int updateByPrimaryKey(SportSuggestionUser record);
}