package com.tianfang.business.mapper;

import com.tianfang.business.pojo.SportFutureStarBlog;
import com.tianfang.business.pojo.SportFutureStarBlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportFutureStarBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int countByExample(SportFutureStarBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int deleteByExample(SportFutureStarBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int insert(SportFutureStarBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int insertSelective(SportFutureStarBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    List<SportFutureStarBlog> selectByExampleWithBLOBs(SportFutureStarBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    List<SportFutureStarBlog> selectByExample(SportFutureStarBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    SportFutureStarBlog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportFutureStarBlog record, @Param("example") SportFutureStarBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") SportFutureStarBlog record, @Param("example") SportFutureStarBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int updateByExample(@Param("record") SportFutureStarBlog record, @Param("example") SportFutureStarBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int updateByPrimaryKeySelective(SportFutureStarBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SportFutureStarBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_future_star_blog
     *
     * @mbggenerated Fri Nov 27 18:05:26 CST 2015
     */
    int updateByPrimaryKey(SportFutureStarBlog record);
}