package com.tianfang.business.mapper;

import com.tianfang.business.pojo.SportQuestionAnswer;
import com.tianfang.business.pojo.SportQuestionAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportQuestionAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int countByExample(SportQuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int deleteByExample(SportQuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int insert(SportQuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int insertSelective(SportQuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    List<SportQuestionAnswer> selectByExample(SportQuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    SportQuestionAnswer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportQuestionAnswer record, @Param("example") SportQuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int updateByExample(@Param("record") SportQuestionAnswer record, @Param("example") SportQuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int updateByPrimaryKeySelective(SportQuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_question_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    int updateByPrimaryKey(SportQuestionAnswer record);
}