package com.tianfang.business.mapper;

import com.tianfang.business.dto.SportHomeDto;
import com.tianfang.common.model.PageQuery;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SportHomeMapperX {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int countByExample(SportHomeDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int deleteByExample(SportHomeDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int insert(SportHomeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int insertSelective(SportHomeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    List<SportHomeDto> selectByExample(SportHomeDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    SportHomeDto selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportHomeDto record, @Param("example") SportHomeDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int updateByExample(@Param("record") SportHomeDto record, @Param("example") SportHomeDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int updateByPrimaryKeySelective(SportHomeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_home
     *
     * @mbggenerated Fri Nov 13 13:33:47 CST 2015
     */
    int updateByPrimaryKey(SportHomeDto record);
    
    /**
     * 新增SportHomeDto记录
     * @param dto
     * @return
     * @2015年11月18日
     */
    boolean addHomeRecord(SportHomeDto dto);

    /**
     * 删除SportHomeDto记录
     * @param hid
     * @return
     * @2015年11月18日
     */
	boolean deleteHRecord(String hid);

	/**
	 * 更新SportHomeDto记录
	 * @param dto
	 * @return
	 * @2015年11月18日
	 */
	Integer updateHRecord(SportHomeDto dto);

	/**
	 * 根据条件查询SportHomeDto记录
	 * @param param
	 * @return
	 * @2015年11月18日
	 */
	List<SportHomeDto> findHRecords(Map<String, Object> param);
	
	/**
	 * 根据条件查询记录条数
	 * @param param
	 * @return
	 * @2015年11月18日
	 */
	Long countSum(Map<String, Object> param);
	
	/**
	 * 根据条件查询最新的n条记录(order by create_time desc)
	 * @param param
	 * @return
	 */
	List<SportHomeDto> findNRecords(Map<String, Object> param);
}