package com.tianfang.business.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.tianfang.business.dto.SportTeamDto;

public interface SportTeamMapperX {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int countByExample(SportTeamDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int deleteByExample(SportTeamDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int insert(SportTeamDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int insertSelective(SportTeamDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    List<SportTeamDto> selectByExample(SportTeamDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    SportTeamDto selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportTeamDto record, @Param("example") SportTeamDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int updateByExample(@Param("record") SportTeamDto record, @Param("example") SportTeamDto example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int updateByPrimaryKeySelective(SportTeamDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team
     *
     * @mbggenerated Mon Nov 16 10:09:09 CST 2015
     */
    int updateByPrimaryKey(SportTeamDto record);
    
    /**
     * 查询所有队伍信息
     * @return
     * @2015年11月16日
     */
    List<SportTeamDto> findAllTeams();
    
    /**
     * 根据id查询队伍信息
     * @param id
     * @return
     */
    SportTeamDto findById(String id);
}