package com.tianfang.business.mapper;

import com.tianfang.business.pojo.SportInformation;
import com.tianfang.business.pojo.SportInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int countByExample(SportInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int deleteByExample(SportInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int insert(SportInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int insertSelective(SportInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    List<SportInformation> selectByExample(SportInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    SportInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportInformation record, @Param("example") SportInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int updateByExample(@Param("record") SportInformation record, @Param("example") SportInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int updateByPrimaryKeySelective(SportInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_information
     *
     * @mbggenerated Thu Dec 03 14:20:29 CST 2015
     */
    int updateByPrimaryKey(SportInformation record);
}