package com.tianfang.business.mapper;

import com.tianfang.business.pojo.SportTeamMembers;
import com.tianfang.business.pojo.SportTeamMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportTeamMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int countByExample(SportTeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int deleteByExample(SportTeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int insert(SportTeamMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int insertSelective(SportTeamMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    List<SportTeamMembers> selectByExample(SportTeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    SportTeamMembers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int updateByExampleSelective(@Param("record") SportTeamMembers record, @Param("example") SportTeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int updateByExample(@Param("record") SportTeamMembers record, @Param("example") SportTeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int updateByPrimaryKeySelective(SportTeamMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_team_members
     *
     * @mbggenerated Tue Dec 08 12:35:23 CST 2015
     */
    int updateByPrimaryKey(SportTeamMembers record);
}