package com.tianfang.order.pojo;

import java.io.Serializable;
import java.util.Date;

public class SportMCategory implements Serializable  {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.type_id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.parent_id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.category_name
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.category_pic
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private String categoryPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.category_order
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private Integer categoryOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.is_show
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.create_time
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.last_update_time
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_m_category.stat
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.id
     *
     * @return the value of sport_m_category.id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.id
     *
     * @param id the value for sport_m_category.id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.type_id
     *
     * @return the value of sport_m_category.type_id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.type_id
     *
     * @param typeId the value for sport_m_category.type_id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.parent_id
     *
     * @return the value of sport_m_category.parent_id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.parent_id
     *
     * @param parentId the value for sport_m_category.parent_id
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.category_name
     *
     * @return the value of sport_m_category.category_name
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.category_name
     *
     * @param categoryName the value for sport_m_category.category_name
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.category_pic
     *
     * @return the value of sport_m_category.category_pic
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public String getCategoryPic() {
        return categoryPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.category_pic
     *
     * @param categoryPic the value for sport_m_category.category_pic
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setCategoryPic(String categoryPic) {
        this.categoryPic = categoryPic == null ? null : categoryPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.category_order
     *
     * @return the value of sport_m_category.category_order
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public Integer getCategoryOrder() {
        return categoryOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.category_order
     *
     * @param categoryOrder the value for sport_m_category.category_order
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setCategoryOrder(Integer categoryOrder) {
        this.categoryOrder = categoryOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.is_show
     *
     * @return the value of sport_m_category.is_show
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.is_show
     *
     * @param isShow the value for sport_m_category.is_show
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.create_time
     *
     * @return the value of sport_m_category.create_time
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.create_time
     *
     * @param createTime the value for sport_m_category.create_time
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.last_update_time
     *
     * @return the value of sport_m_category.last_update_time
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.last_update_time
     *
     * @param lastUpdateTime the value for sport_m_category.last_update_time
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_m_category.stat
     *
     * @return the value of sport_m_category.stat
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_m_category.stat
     *
     * @param stat the value for sport_m_category.stat
     *
     * @mbggenerated Wed Jan 06 10:00:40 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}