package com.tianfang.admin.pojo;

import java.util.Date;

public class SportMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.create_time
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.descript
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.leaf
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.left_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String leftMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.menu_id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.menu_title
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String menuTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.parent_id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.last_update_time
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.stat
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.orderby
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private Integer orderby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.menu_url
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_menu.menu_icon
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    private String menuIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.id
     *
     * @return the value of sport_menu.id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.id
     *
     * @param id the value for sport_menu.id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.create_time
     *
     * @return the value of sport_menu.create_time
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.create_time
     *
     * @param createTime the value for sport_menu.create_time
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.descript
     *
     * @return the value of sport_menu.descript
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.descript
     *
     * @param descript the value for sport_menu.descript
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.leaf
     *
     * @return the value of sport_menu.leaf
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.leaf
     *
     * @param leaf the value for sport_menu.leaf
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setLeaf(String leaf) {
        this.leaf = leaf == null ? null : leaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.left_menu
     *
     * @return the value of sport_menu.left_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getLeftMenu() {
        return leftMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.left_menu
     *
     * @param leftMenu the value for sport_menu.left_menu
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setLeftMenu(String leftMenu) {
        this.leftMenu = leftMenu == null ? null : leftMenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.menu_id
     *
     * @return the value of sport_menu.menu_id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.menu_id
     *
     * @param menuId the value for sport_menu.menu_id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.menu_title
     *
     * @return the value of sport_menu.menu_title
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getMenuTitle() {
        return menuTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.menu_title
     *
     * @param menuTitle the value for sport_menu.menu_title
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setMenuTitle(String menuTitle) {
        this.menuTitle = menuTitle == null ? null : menuTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.parent_id
     *
     * @return the value of sport_menu.parent_id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.parent_id
     *
     * @param parentId the value for sport_menu.parent_id
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.last_update_time
     *
     * @return the value of sport_menu.last_update_time
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.last_update_time
     *
     * @param lastUpdateTime the value for sport_menu.last_update_time
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.stat
     *
     * @return the value of sport_menu.stat
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.stat
     *
     * @param stat the value for sport_menu.stat
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.orderby
     *
     * @return the value of sport_menu.orderby
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.orderby
     *
     * @param orderby the value for sport_menu.orderby
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.menu_url
     *
     * @return the value of sport_menu.menu_url
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.menu_url
     *
     * @param menuUrl the value for sport_menu.menu_url
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_menu.menu_icon
     *
     * @return the value of sport_menu.menu_icon
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_menu.menu_icon
     *
     * @param menuIcon the value for sport_menu.menu_icon
     *
     * @mbggenerated Fri Nov 13 12:56:17 CST 2015
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon == null ? null : menuIcon.trim();
    }
}