package com.tianfang.admin.pojo;

import java.util.Date;

public class SportAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_admin.id
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_admin.account
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_admin.pass_word
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_admin.create_time
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_admin.update_time
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_admin.stat
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_admin.id
     *
     * @return the value of sport_admin.id
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_admin.id
     *
     * @param id the value for sport_admin.id
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_admin.account
     *
     * @return the value of sport_admin.account
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_admin.account
     *
     * @param account the value for sport_admin.account
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_admin.pass_word
     *
     * @return the value of sport_admin.pass_word
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_admin.pass_word
     *
     * @param passWord the value for sport_admin.pass_word
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_admin.create_time
     *
     * @return the value of sport_admin.create_time
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_admin.create_time
     *
     * @param createTime the value for sport_admin.create_time
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_admin.update_time
     *
     * @return the value of sport_admin.update_time
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_admin.update_time
     *
     * @param updateTime the value for sport_admin.update_time
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_admin.stat
     *
     * @return the value of sport_admin.stat
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_admin.stat
     *
     * @param stat the value for sport_admin.stat
     *
     * @mbggenerated Fri Nov 13 12:53:33 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}