package com.tianfang.order.mapper;

import com.tianfang.order.pojo.SportMProductSpecValues;
import com.tianfang.order.pojo.SportMProductSpecValuesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportMProductSpecValuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int countByExample(SportMProductSpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int deleteByExample(SportMProductSpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int insert(SportMProductSpecValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int insertSelective(SportMProductSpecValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    List<SportMProductSpecValues> selectByExample(SportMProductSpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    SportMProductSpecValues selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") SportMProductSpecValues record, @Param("example") SportMProductSpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int updateByExample(@Param("record") SportMProductSpecValues record, @Param("example") SportMProductSpecValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int updateByPrimaryKeySelective(SportMProductSpecValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_product_spec_values
     *
     * @mbggenerated Wed Jan 20 16:10:39 CST 2016
     */
    int updateByPrimaryKey(SportMProductSpecValues record);
}