package com.tianfang.order.mapper;

import com.tianfang.order.pojo.SportMOrderInfo;
import com.tianfang.order.pojo.SportMOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportMOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int countByExample(SportMOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int deleteByExample(SportMOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int insert(SportMOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int insertSelective(SportMOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    List<SportMOrderInfo> selectByExample(SportMOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    SportMOrderInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int updateByExampleSelective(@Param("record") SportMOrderInfo record, @Param("example") SportMOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int updateByExample(@Param("record") SportMOrderInfo record, @Param("example") SportMOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int updateByPrimaryKeySelective(SportMOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_order_info
     *
     * @mbggenerated Thu Jan 14 14:12:49 CST 2016
     */
    int updateByPrimaryKey(SportMOrderInfo record);
}