package com.tianfang.order.mapper;

import com.tianfang.order.pojo.SportMShippingAddress;
import com.tianfang.order.pojo.SportMShippingAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportMShippingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int countByExample(SportMShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int deleteByExample(SportMShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int insert(SportMShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int insertSelective(SportMShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    List<SportMShippingAddress> selectByExample(SportMShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    SportMShippingAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") SportMShippingAddress record, @Param("example") SportMShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int updateByExample(@Param("record") SportMShippingAddress record, @Param("example") SportMShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int updateByPrimaryKeySelective(SportMShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_m_shipping_address
     *
     * @mbggenerated Thu Jan 21 14:55:25 CST 2016
     */
    int updateByPrimaryKey(SportMShippingAddress record);
}