package com.tianfang.business.pojo;

import java.util.Date;

public class SportHome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.id
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.pic_video_url
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private String picVideoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.type
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.pic_marked
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private Integer picMarked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.title
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.href_url
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private String hrefUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.content
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.create_time
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.last_update_time
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.stat
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_home.micro_pic
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    private String microPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.id
     *
     * @return the value of sport_home.id
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.id
     *
     * @param id the value for sport_home.id
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.pic_video_url
     *
     * @return the value of sport_home.pic_video_url
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public String getPicVideoUrl() {
        return picVideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.pic_video_url
     *
     * @param picVideoUrl the value for sport_home.pic_video_url
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setPicVideoUrl(String picVideoUrl) {
        this.picVideoUrl = picVideoUrl == null ? null : picVideoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.type
     *
     * @return the value of sport_home.type
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.type
     *
     * @param type the value for sport_home.type
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.pic_marked
     *
     * @return the value of sport_home.pic_marked
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public Integer getPicMarked() {
        return picMarked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.pic_marked
     *
     * @param picMarked the value for sport_home.pic_marked
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setPicMarked(Integer picMarked) {
        this.picMarked = picMarked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.title
     *
     * @return the value of sport_home.title
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.title
     *
     * @param title the value for sport_home.title
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.href_url
     *
     * @return the value of sport_home.href_url
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public String getHrefUrl() {
        return hrefUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.href_url
     *
     * @param hrefUrl the value for sport_home.href_url
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setHrefUrl(String hrefUrl) {
        this.hrefUrl = hrefUrl == null ? null : hrefUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.content
     *
     * @return the value of sport_home.content
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.content
     *
     * @param content the value for sport_home.content
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.create_time
     *
     * @return the value of sport_home.create_time
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.create_time
     *
     * @param createTime the value for sport_home.create_time
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.last_update_time
     *
     * @return the value of sport_home.last_update_time
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.last_update_time
     *
     * @param lastUpdateTime the value for sport_home.last_update_time
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.stat
     *
     * @return the value of sport_home.stat
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.stat
     *
     * @param stat the value for sport_home.stat
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_home.micro_pic
     *
     * @return the value of sport_home.micro_pic
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public String getMicroPic() {
        return microPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_home.micro_pic
     *
     * @param microPic the value for sport_home.micro_pic
     *
     * @mbggenerated Mon Dec 07 11:39:16 CST 2015
     */
    public void setMicroPic(String microPic) {
        this.microPic = microPic == null ? null : microPic.trim();
    }
}