package com.tianfang.business.pojo;

import java.util.Date;

public class SportSfAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_sf_answer.id
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_sf_answer.answer_name
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    private String answerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_sf_answer.create_time
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_sf_answer.last_update_time
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_sf_answer.stat
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_sf_answer.question
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    private String question;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_sf_answer.id
     *
     * @return the value of sport_sf_answer.id
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_sf_answer.id
     *
     * @param id the value for sport_sf_answer.id
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_sf_answer.answer_name
     *
     * @return the value of sport_sf_answer.answer_name
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public String getAnswerName() {
        return answerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_sf_answer.answer_name
     *
     * @param answerName the value for sport_sf_answer.answer_name
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public void setAnswerName(String answerName) {
        this.answerName = answerName == null ? null : answerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_sf_answer.create_time
     *
     * @return the value of sport_sf_answer.create_time
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_sf_answer.create_time
     *
     * @param createTime the value for sport_sf_answer.create_time
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_sf_answer.last_update_time
     *
     * @return the value of sport_sf_answer.last_update_time
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_sf_answer.last_update_time
     *
     * @param lastUpdateTime the value for sport_sf_answer.last_update_time
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_sf_answer.stat
     *
     * @return the value of sport_sf_answer.stat
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_sf_answer.stat
     *
     * @param stat the value for sport_sf_answer.stat
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_sf_answer.question
     *
     * @return the value of sport_sf_answer.question
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_sf_answer.question
     *
     * @param question the value for sport_sf_answer.question
     *
     * @mbggenerated Tue Dec 29 15:34:00 CST 2015
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }
}