package com.tianfang.business.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SportSuggestionUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public SportSuggestionUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSfTypeIsNull() {
            addCriterion("sf_type is null");
            return (Criteria) this;
        }

        public Criteria andSfTypeIsNotNull() {
            addCriterion("sf_type is not null");
            return (Criteria) this;
        }

        public Criteria andSfTypeEqualTo(Integer value) {
            addCriterion("sf_type =", value, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeNotEqualTo(Integer value) {
            addCriterion("sf_type <>", value, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeGreaterThan(Integer value) {
            addCriterion("sf_type >", value, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("sf_type >=", value, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeLessThan(Integer value) {
            addCriterion("sf_type <", value, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeLessThanOrEqualTo(Integer value) {
            addCriterion("sf_type <=", value, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeIn(List<Integer> values) {
            addCriterion("sf_type in", values, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeNotIn(List<Integer> values) {
            addCriterion("sf_type not in", values, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeBetween(Integer value1, Integer value2) {
            addCriterion("sf_type between", value1, value2, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("sf_type not between", value1, value2, "sfType");
            return (Criteria) this;
        }

        public Criteria andSfUnameIsNull() {
            addCriterion("sf_uname is null");
            return (Criteria) this;
        }

        public Criteria andSfUnameIsNotNull() {
            addCriterion("sf_uname is not null");
            return (Criteria) this;
        }

        public Criteria andSfUnameEqualTo(String value) {
            addCriterion("sf_uname =", value, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameNotEqualTo(String value) {
            addCriterion("sf_uname <>", value, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameGreaterThan(String value) {
            addCriterion("sf_uname >", value, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameGreaterThanOrEqualTo(String value) {
            addCriterion("sf_uname >=", value, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameLessThan(String value) {
            addCriterion("sf_uname <", value, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameLessThanOrEqualTo(String value) {
            addCriterion("sf_uname <=", value, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameLike(String value) {
            addCriterion("sf_uname like", value, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameNotLike(String value) {
            addCriterion("sf_uname not like", value, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameIn(List<String> values) {
            addCriterion("sf_uname in", values, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameNotIn(List<String> values) {
            addCriterion("sf_uname not in", values, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameBetween(String value1, String value2) {
            addCriterion("sf_uname between", value1, value2, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfUnameNotBetween(String value1, String value2) {
            addCriterion("sf_uname not between", value1, value2, "sfUname");
            return (Criteria) this;
        }

        public Criteria andSfPhoneIsNull() {
            addCriterion("sf_phone is null");
            return (Criteria) this;
        }

        public Criteria andSfPhoneIsNotNull() {
            addCriterion("sf_phone is not null");
            return (Criteria) this;
        }

        public Criteria andSfPhoneEqualTo(String value) {
            addCriterion("sf_phone =", value, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneNotEqualTo(String value) {
            addCriterion("sf_phone <>", value, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneGreaterThan(String value) {
            addCriterion("sf_phone >", value, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("sf_phone >=", value, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneLessThan(String value) {
            addCriterion("sf_phone <", value, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneLessThanOrEqualTo(String value) {
            addCriterion("sf_phone <=", value, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneLike(String value) {
            addCriterion("sf_phone like", value, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneNotLike(String value) {
            addCriterion("sf_phone not like", value, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneIn(List<String> values) {
            addCriterion("sf_phone in", values, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneNotIn(List<String> values) {
            addCriterion("sf_phone not in", values, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneBetween(String value1, String value2) {
            addCriterion("sf_phone between", value1, value2, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfPhoneNotBetween(String value1, String value2) {
            addCriterion("sf_phone not between", value1, value2, "sfPhone");
            return (Criteria) this;
        }

        public Criteria andSfEmailIsNull() {
            addCriterion("sf_email is null");
            return (Criteria) this;
        }

        public Criteria andSfEmailIsNotNull() {
            addCriterion("sf_email is not null");
            return (Criteria) this;
        }

        public Criteria andSfEmailEqualTo(String value) {
            addCriterion("sf_email =", value, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailNotEqualTo(String value) {
            addCriterion("sf_email <>", value, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailGreaterThan(String value) {
            addCriterion("sf_email >", value, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailGreaterThanOrEqualTo(String value) {
            addCriterion("sf_email >=", value, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailLessThan(String value) {
            addCriterion("sf_email <", value, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailLessThanOrEqualTo(String value) {
            addCriterion("sf_email <=", value, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailLike(String value) {
            addCriterion("sf_email like", value, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailNotLike(String value) {
            addCriterion("sf_email not like", value, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailIn(List<String> values) {
            addCriterion("sf_email in", values, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailNotIn(List<String> values) {
            addCriterion("sf_email not in", values, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailBetween(String value1, String value2) {
            addCriterion("sf_email between", value1, value2, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfEmailNotBetween(String value1, String value2) {
            addCriterion("sf_email not between", value1, value2, "sfEmail");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackIsNull() {
            addCriterion("sf_feedback is null");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackIsNotNull() {
            addCriterion("sf_feedback is not null");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackEqualTo(String value) {
            addCriterion("sf_feedback =", value, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackNotEqualTo(String value) {
            addCriterion("sf_feedback <>", value, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackGreaterThan(String value) {
            addCriterion("sf_feedback >", value, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackGreaterThanOrEqualTo(String value) {
            addCriterion("sf_feedback >=", value, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackLessThan(String value) {
            addCriterion("sf_feedback <", value, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackLessThanOrEqualTo(String value) {
            addCriterion("sf_feedback <=", value, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackLike(String value) {
            addCriterion("sf_feedback like", value, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackNotLike(String value) {
            addCriterion("sf_feedback not like", value, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackIn(List<String> values) {
            addCriterion("sf_feedback in", values, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackNotIn(List<String> values) {
            addCriterion("sf_feedback not in", values, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackBetween(String value1, String value2) {
            addCriterion("sf_feedback between", value1, value2, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfFeedbackNotBetween(String value1, String value2) {
            addCriterion("sf_feedback not between", value1, value2, "sfFeedback");
            return (Criteria) this;
        }

        public Criteria andSfPictureIsNull() {
            addCriterion("sf_picture is null");
            return (Criteria) this;
        }

        public Criteria andSfPictureIsNotNull() {
            addCriterion("sf_picture is not null");
            return (Criteria) this;
        }

        public Criteria andSfPictureEqualTo(String value) {
            addCriterion("sf_picture =", value, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureNotEqualTo(String value) {
            addCriterion("sf_picture <>", value, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureGreaterThan(String value) {
            addCriterion("sf_picture >", value, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureGreaterThanOrEqualTo(String value) {
            addCriterion("sf_picture >=", value, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureLessThan(String value) {
            addCriterion("sf_picture <", value, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureLessThanOrEqualTo(String value) {
            addCriterion("sf_picture <=", value, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureLike(String value) {
            addCriterion("sf_picture like", value, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureNotLike(String value) {
            addCriterion("sf_picture not like", value, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureIn(List<String> values) {
            addCriterion("sf_picture in", values, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureNotIn(List<String> values) {
            addCriterion("sf_picture not in", values, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureBetween(String value1, String value2) {
            addCriterion("sf_picture between", value1, value2, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andSfPictureNotBetween(String value1, String value2) {
            addCriterion("sf_picture not between", value1, value2, "sfPicture");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 24 16:57:29 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sport_suggestion_user
     *
     * @mbggenerated Thu Dec 24 16:57:29 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}