package com.tianfang.business.pojo;

import java.util.Date;

public class SportQuestionAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_question_answer.id
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_question_answer.sf_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    private String sfAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_question_answer.sf_question
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    private String sfQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_question_answer.create_time
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_question_answer.last_update_time
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sport_question_answer.stat
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_question_answer.id
     *
     * @return the value of sport_question_answer.id
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_question_answer.id
     *
     * @param id the value for sport_question_answer.id
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_question_answer.sf_answer
     *
     * @return the value of sport_question_answer.sf_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public String getSfAnswer() {
        return sfAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_question_answer.sf_answer
     *
     * @param sfAnswer the value for sport_question_answer.sf_answer
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public void setSfAnswer(String sfAnswer) {
        this.sfAnswer = sfAnswer == null ? null : sfAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_question_answer.sf_question
     *
     * @return the value of sport_question_answer.sf_question
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public String getSfQuestion() {
        return sfQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_question_answer.sf_question
     *
     * @param sfQuestion the value for sport_question_answer.sf_question
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public void setSfQuestion(String sfQuestion) {
        this.sfQuestion = sfQuestion == null ? null : sfQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_question_answer.create_time
     *
     * @return the value of sport_question_answer.create_time
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_question_answer.create_time
     *
     * @param createTime the value for sport_question_answer.create_time
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_question_answer.last_update_time
     *
     * @return the value of sport_question_answer.last_update_time
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_question_answer.last_update_time
     *
     * @param lastUpdateTime the value for sport_question_answer.last_update_time
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sport_question_answer.stat
     *
     * @return the value of sport_question_answer.stat
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sport_question_answer.stat
     *
     * @param stat the value for sport_question_answer.stat
     *
     * @mbggenerated Thu Dec 24 16:58:35 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}