package com.tianfang.onteach.mapper;

import com.tianfang.onteach.pojo.SportOnlineTeachColumn;
import com.tianfang.onteach.pojo.SportOnlineTeachColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportOnlineTeachColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int countByExample(SportOnlineTeachColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int deleteByExample(SportOnlineTeachColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int insert(SportOnlineTeachColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int insertSelective(SportOnlineTeachColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    List<SportOnlineTeachColumn> selectByExample(SportOnlineTeachColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    SportOnlineTeachColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") SportOnlineTeachColumn record, @Param("example") SportOnlineTeachColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int updateByExample(@Param("record") SportOnlineTeachColumn record, @Param("example") SportOnlineTeachColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int updateByPrimaryKeySelective(SportOnlineTeachColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sport_online_teach_column
     *
     * @mbggenerated Wed Jan 20 09:40:29 CST 2016
     */
    int updateByPrimaryKey(SportOnlineTeachColumn record);
}