package com.tianfang.train.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tianfang.train.pojo.AssistantMapping;
import com.tianfang.train.pojo.AssistantMappingExample;

public interface AssistantMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int countByExample(AssistantMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int deleteByExample(AssistantMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int insert(AssistantMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int insertSelective(AssistantMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    List<AssistantMapping> selectByExample(AssistantMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    AssistantMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") AssistantMapping record, @Param("example") AssistantMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int updateByExample(@Param("record") AssistantMapping record, @Param("example") AssistantMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int updateByPrimaryKeySelective(AssistantMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_mapping
     *
     * @mbggenerated Fri Sep 18 15:04:43 CST 2015
     */
    int updateByPrimaryKey(AssistantMapping record);
}