package com.tianfang.train.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tianfang.train.pojo.TrainingAssistantAddressTime;
import com.tianfang.train.pojo.TrainingAssistantAddressTimeExample;

public interface TrainingAssistantAddressTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int countByExample(TrainingAssistantAddressTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int deleteByExample(TrainingAssistantAddressTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int insert(TrainingAssistantAddressTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int insertSelective(TrainingAssistantAddressTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    List<TrainingAssistantAddressTime> selectByExample(TrainingAssistantAddressTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    TrainingAssistantAddressTime selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") TrainingAssistantAddressTime record, @Param("example") TrainingAssistantAddressTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int updateByExample(@Param("record") TrainingAssistantAddressTime record, @Param("example") TrainingAssistantAddressTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int updateByPrimaryKeySelective(TrainingAssistantAddressTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_assistant_address_time
     *
     * @mbggenerated Tue Sep 22 10:11:42 CST 2015
     */
    int updateByPrimaryKey(TrainingAssistantAddressTime record);
}