package com.tianfang.train.mapper;

import com.tianfang.train.pojo.TrainingMenu;
import com.tianfang.train.pojo.TrainingMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrainingMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int countByExample(TrainingMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int deleteByExample(TrainingMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int insert(TrainingMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int insertSelective(TrainingMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    List<TrainingMenu> selectByExample(TrainingMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    TrainingMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int updateByExampleSelective(@Param("record") TrainingMenu record, @Param("example") TrainingMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int updateByExample(@Param("record") TrainingMenu record, @Param("example") TrainingMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int updateByPrimaryKeySelective(TrainingMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_menu
     *
     * @mbggenerated Mon Oct 26 13:26:25 CST 2015
     */
    int updateByPrimaryKey(TrainingMenu record);
}